import os
import json
import librosa
import numpy as np
from typing import Any, Tuple
import scipy
import soundfile as sf
import torch
import random
from collections import defaultdict
from pytorch_lightning import LightningDataModule
# from pytorch_lightning.core.mixins import HyperparametersMixin
import torchaudio
from torch.utils.data import ConcatDataset, DataLoader, Dataset
from typing import Any, Dict, Optional, Tuple
from pytorch_lightning.utilities import rank_zero_only

@rank_zero_only
def print_(message: str):
    print(message)


def normalize_tensor_wav(wav_tensor, eps=1e-8, std=None):
    mean = wav_tensor.mean(-1, keepdim=True)
    if std is None:
        std = wav_tensor.std(-1, keepdim=True)
    return (wav_tensor - mean) / (std + eps)

def find_bottom_directories(root_dir):
    bottom_directories = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # A directory with no subdirectories is considered the bottom-level directory
        if not dirnames:
            bottom_directories.append(dirpath)
    return bottom_directories

def compute_mch_rms_dB(mch_wav, fs=16000, energy_thresh=-50):
    """Return the wav RMS calculated only in the active portions"""
    mean_square = max(1e-20, torch.mean(mch_wav ** 2))
    return 10 * np.log10(mean_square)
    
class Libri2MixDataset(Dataset):
    def __init__(
        self,
        json_dir: str = "",
        n_src: int = 1,
        sample_rate: int = 16000,
        segment: float = 4.0,
        normalize_audio: bool = False,
        **kwargs
    ) -> None:
        super().__init__()
        self.EPS = 1e-8
        if json_dir == None:
            raise ValueError("JSON DIR is None!")
        
        self.json_dir = json_dir
        self.sample_rate = sample_rate
        self.normalize_audio = normalize_audio
        
        if segment is None:
            self.seg_len = None
            
        else:
            self.seg_len = int(segment * sample_rate)
        
        self.test = (self.seg_len is None)
            
        # Read the unified JSON generated by the preprocessing script
        data_json = os.path.join(json_dir, "data.json")
        if not os.path.exists(data_json):
            raise FileNotFoundError(f"data.json not found in {json_dir}, run the generation script first!")

        with open(data_json, "r") as f:
            self.data_list = json.load(f)

        if not self.test:
            self.data_list = [item for item in self.data_list if item['length'] >= self.seg_len]
            
        self.length = len(self.data_list)
        print(f"Dataset loaded: {json_dir}, valid samples: {self.length}")

    



    def __len__(self):
        return self.length


    def preprocess_audio_only(self, idx: int):
            """
            Load a single sample: reads Mix, Target audio and d-vector,
            crops to seg_len during training, keeps full length during test.
            """
            # 1. Retrieve sample path info from data.json
            item = self.data_list[idx]
            
            # 2. Determine read bounds (crop during training, full during test)
            if self.test:
                start, stop = 0, None

            else:
                if item['length'] <= self.seg_len:
                    start, stop = 0, None
                else:
                    rand_start = np.random.randint(0, item['length'] - self.seg_len)
                    start, stop = rand_start, rand_start + self.seg_len

            # 3. Load mixture and target audio
            x, _ = sf.read(item['mix'], start=start, stop=stop, dtype="float32")
            s, _ = sf.read(item['target'], start=start, stop=stop, dtype="float32")
            
            mixture = torch.from_numpy(x)
            target = torch.from_numpy(s).unsqueeze(0)  # shape (1, T)

            # 4. Load speaker embedding (d-vector)
            try:
                d_vector = np.load(item['dvector'])
                d_vector = torch.from_numpy(d_vector).float()
                d_vector = d_vector.squeeze()  # ensure shape [192]
            except Exception as e:
                # Fall back to zero vector to avoid crash on bad samples
                print(f"Warning: Load dvector failed for {item['dvector']}: {e}")
                d_vector = torch.zeros(192)

            # 5. Normalize audio if configured
            if self.normalize_audio:
                m_std = mixture.std(-1, keepdim=True)
                mixture = (mixture) / (m_std + self.EPS)
                target = (target) / (m_std + self.EPS)

            filename = item['mix'].split("/")[-1]
            return mixture, target, d_vector, filename


    def __getitem__(self, index: int):
        mixture, target, d_vector, _ = self.preprocess_audio_only(index)
        return mixture, target, d_vector

class Libri2MixModuleRemix(LightningDataModule):
    def __init__(
        self,
        train_dir: str,
        valid_dir: str,
        test_dir: str,
        n_src: int = 2,
        sample_rate: int = 16000,
        segment: float = 4.0,
        normalize_audio: bool = False,
        batch_size: int = 64,
        num_workers: int = 0,
        pin_memory: bool = False,
        persistent_workers: bool = False,
    ) -> None:
        super().__init__()
        self.save_hyperparameters(logger=False)
        
        self.data_train: Optional[Dataset] = None
        self.data_val: Optional[Dataset] = None
        self.data_test: Optional[Dataset] = None
        
    def setup(self, stage: Optional[str] = None) -> None:
        """Load data. Set variables: `self.data_train`, `self.data_val`, `self.data_test`.

        This method is called by Lightning before `trainer.fit()`, `trainer.validate()`, `trainer.test()`, and
        `trainer.predict()`, so be careful not to execute things like random split twice! Also, it is called after
        `self.prepare_data()` and there is a barrier in between which ensures that all the processes proceed to
        `self.setup()` once the data is prepared and available for use.

        :param stage: The stage to setup. Either `"fit"`, `"validate"`, `"test"`, or `"predict"`. Defaults to ``None``.
        """
        train_emb = "/scratch/s6295509/TSE/TIGER/speaker_embedding/train_embedding"
        dev_emb = "/scratch/s6295509/TSE/TIGER/speaker_embedding/dev_embedding"
        test_emb = "/scratch/s6295509/TSE/TIGER/speaker_embedding/test_embedding"


        
        # load and split datasets only if not loaded already
        if not self.data_train and not self.data_val and not self.data_test:
            self.data_train = Libri2MixDataset(
                json_dir=self.hparams.train_dir,
                n_src=self.hparams.n_src,
                sample_rate=self.hparams.sample_rate,
                segment=self.hparams.segment,
                normalize_audio=self.hparams.normalize_audio,
                emb_root=train_emb,
            )
            self.data_val = Libri2MixDataset(
                json_dir=self.hparams.valid_dir,
                n_src=self.hparams.n_src,
                sample_rate=self.hparams.sample_rate,
                segment=None,
                normalize_audio=self.hparams.normalize_audio,
                emb_root=dev_emb,
            )
            self.data_test = Libri2MixDataset(
                json_dir=self.hparams.test_dir,
                n_src=self.hparams.n_src,
                sample_rate=self.hparams.sample_rate,
                segment=None,
                normalize_audio=self.hparams.normalize_audio,
                emb_root=test_emb,
            )
    
    def train_dataloader(self) -> DataLoader:
        return DataLoader(
            self.data_train,
            batch_size=self.hparams.batch_size,
            num_workers=self.hparams.num_workers,
            shuffle=True,
            pin_memory=True,
        )
        
    def val_dataloader(self) -> DataLoader:
        return DataLoader(
            self.data_val,
            batch_size=1,
            num_workers=self.hparams.num_workers,
            shuffle=False,
            pin_memory=True,
        )
        
    def test_dataloader(self) -> DataLoader:
        return DataLoader(
            self.data_test,
            batch_size=1,
            num_workers=self.hparams.num_workers,
            shuffle=False,
            pin_memory=True,
        )

    @property
    def make_loader(self):
        return self.train_dataloader(), self.val_dataloader(), self.test_dataloader()
        